export const GET_USER_ID_REQUEST = "GET_USER_ID_REQUEST";
export const GET_USER_ID_SUCCESS = "GET_USER_ID_SUCCESS";
export const GET_USER_ID_FAILURE = "GET_USER_ID_FAILURE";

export const POST_USER_ID_REQUEST = "POST_USER_ID_REQUEST";
export const POST_USER_ID_SUCCESS = "POST_USER_ID_SUCCESS";
export const POST_USER_ID_FAILURE = "POST_USER_ID_FAILURE";

export const GET_USER_PROJECT_ID_REQUEST = "GET_USER_PROJECT_ID_REQUEST";
export const GET_USER_PROJECT_ID_SUCCESS = "GET_USER_PROJECT_ID_SUCCESS";
export const GET_USER_PROJECT_ID_FAILURE = "GET_USER_PROJECT_ID_FAILURE";

export const POST_USER_PROJECT_ID_REQUEST = "POST_USER_PROJECT_ID_REQUEST";
export const POST_USER_PROJECT_ID_SUCCESS = "POST_USER_PROJECT_ID_SUCCESS";
export const POST_USER_PROJECT_ID_FAILURE = "POST_USER_PROJECT_ID_FAILURE";

export const POST_USER_TASK_ID_REQUEST = "POST_USER_TASK_ID_REQUEST";
export const POST_USER_TASK_ID_SUCCESS = "POST_USER_TASK_ID_SUCCESS";
export const POST_USER_TASK_ID_FAILURE = "POST_USER_TASK_ID_FAILURE";

export const GET_USER_TASK_REQUEST = "GET_USER_TASK_REQUEST";
export const GET_USER_TASK_SUCCESS = "GET_USER_TASK_SUCCESS";
export const GET_USER_TASK_FAILURE = "GET_USER_TASK_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";
