export const GET_TASK_REQ = "GET_TASK_REQ"
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS"
export const GET_TASK_FAILURE = "GET_TASK_FAILURE"

export const UPDATE_TASK_REQ = "UPDATE_TASK_REQ"
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS"
export const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE"